if GetLocale() == "deDE" then
	-- translated by ?

	-- DuffedUI
	TukuiConfigUILocalization.nameplatedebuffs = "Enable Debufftracking on Nameplates"

	TukuiConfigUILocalization.merchantautoguildrepair = "Enable automatic repair from Guildbank (if it possible)"

	TukuiConfigUILocalization.generalnormalfont = "Use normal font instead of pixelfont"
	TukuiConfigUILocalization.generalthreatbar = "Set threatbar to the right Chattabbackground"
	TukuiConfigUILocalization.generaloverridehightolow = "Use Lowres-Layout on Highres"

	TukuiConfigUILocalization.bagsmovable = "Enable moveable Bags"
	TukuiConfigUILocalization.bagstransparent = "Enable transparent Bagbackground"

	TukuiConfigUILocalization.datatexthonor = "Honor position (0 for disabled)"
	TukuiConfigUILocalization.datatexthonorablekills = "Honorable Kill position (0 for disabled)"
	TukuiConfigUILocalization.datatextclasscolor = "Set textelements to classcolor"
	TukuiConfigUILocalization.datatextblock = "Block position (0 for disabled)"
	TukuiConfigUILocalization.datatextexperience = "Experience position (0 for disabled)"
	TukuiConfigUILocalization.datatextdodge = "Dodge position (0 for disabled)"
	TukuiConfigUILocalization.datatextreputation = "Reputation position (0 for disabled)"
	TukuiConfigUILocalization.datatextmmenu = "Shows mMenu datatext (required: mMenu AddOn)"
	TukuiConfigUILocalization.datatextcolor1 = "Set color for datatext title (is overwritten if classcolor = true)"
	TukuiConfigUILocalization.datatextcolor2 = "Set color for datatext results"

	TukuiConfigUILocalization.unitframeshealthbarcolor = "Set healthbarcolor"
	TukuiConfigUILocalization.unitframesframewidth = "Set framewidth for player & target"
	TukuiConfigUILocalization.unitframesportraitstyle = "Set Portraitstyle (ICON or MODEL)"
	TukuiConfigUILocalization.unitframesdeficitcolor = "Set deficit color"
	TukuiConfigUILocalization.unitframesfader_alpha = "Set Alphavalue for fader"
	TukuiConfigUILocalization.unitframesdebuffrows = "Set debuffrows above target"
	TukuiConfigUILocalization.unitframeslayout = "Set layout for Unitframes (1, 2 or 3)"
	TukuiConfigUILocalization.unitframestotandpetlines = "Enable lines for ToT and Pet"
	TukuiConfigUILocalization.unitframespowerClasscolored = "Set powerbar to classcolor"
	TukuiConfigUILocalization.unitframespercent = "Display percentvalue beside the target & player"
	TukuiConfigUILocalization.unitframesColorGradient = "Enable colorgradient for unitframes"
	TukuiConfigUILocalization.unitframesvengeancebar = "Display vengence instead of threat"
	TukuiConfigUILocalization.unitframesfocusdebuffs = "Enable focus debuffs"
	TukuiConfigUILocalization.unitframeslargefocus = "Enable large focusframe (layout 1 & 2)"
	TukuiConfigUILocalization.unitframesfader = "Enable fader for unitframes (out of combat)"
	TukuiConfigUILocalization.unitframesgridsolo = "Show Grid always"

	TukuiConfigUILocalization.skins = "Skins"
	TukuiConfigUILocalization.skinsdxe = "Enable DXE-Skin"
	TukuiConfigUILocalization.skinsdbm = "Enable DBM-Skin"
	TukuiConfigUILocalization.skinstinydps = "Enable TinyDPS-Skin"
	TukuiConfigUILocalization.skinsbigwigs = "Enable BigWigs-Skin"
	TukuiConfigUILocalization.skinsblizzard = "Enable Blizzard-Skin"
	TukuiConfigUILocalization.skinsskada = "Enable Skada-Skin"
	TukuiConfigUILocalization.skinsomen = "Enable Omen-Skin"
	TukuiConfigUILocalization.skinsrecount = "Enable Recountskin"
	TukuiConfigUILocalization.skinsbackground = "Enable Addonbackground"
	TukuiConfigUILocalization.skinstoggle = "Toggle AddonBackground in- / outfight"

	TukuiConfigUILocalization.rcd = "RaidCooldowns"
	TukuiConfigUILocalization.rcdenable = "Enable Raidcooldownmonitor"
	TukuiConfigUILocalization.rcdraid = "Enable Raid-Output"
	TukuiConfigUILocalization.rcdparty = "Enable Party-Output"
	TukuiConfigUILocalization.rcdarena = "Enable PvP-Output"

	TukuiConfigUILocalization.tooltipilvl = "Displays average itemlevel on tooltip"
	TukuiConfigUILocalization.tooltipshowspellid = "Show SpellID on tooltip"

	TukuiConfigUILocalization.castbar = "Castbar"
	TukuiConfigUILocalization.castbarenable = "Enable castbar"
	TukuiConfigUILocalization.castbarcblatency = "Show cast bar latency"
	TukuiConfigUILocalization.castbarcbicons = "Show icons on cast bar"
	TukuiConfigUILocalization.castbarfocuswidth = "Set width of focuscastbar"

	TukuiConfigUILocalization.classtimer = "Classtimer"
	TukuiConfigUILocalization.classtimerenable = "Enable Classtimer"
	TukuiConfigUILocalization.classtimertargetdebuffcolor = "Set color for debuffbars"
	TukuiConfigUILocalization.classtimertargetdebuffs = "Enable bars above targetdebuffs (not recommended)"
	TukuiConfigUILocalization.classtimertrinketcolor = "Set color for trinketbars"
	TukuiConfigUILocalization.classtimerplayercolor = "Set color for playerbars"
	TukuiConfigUILocalization.classtimertargetbuffcolor = "Set color for target buffbars"

	TukuiConfigUILocalization.misc = "Misc Options"
	TukuiConfigUILocalization.miscsesenable = "Enable Specswitcher"
	TukuiConfigUILocalization.miscswingtimerenable = "Enable Swingtimer"
	TukuiConfigUILocalization.miscsesgearswap = "Enable automatic gearswap @respec"
	TukuiConfigUILocalization.miscsComboenergybar = "Enable Energybar on sCombo"
	TukuiConfigUILocalization.miscsesset1 = "Set set fpr Mainspec"
	TukuiConfigUILocalization.miscswingtimercolor = "Set color for Swingtimer"
	TukuiConfigUILocalization.miscsComboenable = "Enable sCombo"
	TukuiConfigUILocalization.miscswingtimerwidth = "Set width of Swingtimer"
	TukuiConfigUILocalization.miscsesenablegear = "Enable gearset for Specswitcher"
	TukuiConfigUILocalization.miscbossicons = "Enable alternativ bossicons"
	TukuiConfigUILocalization.miscswingtimerheight = "Set height for Swingtimer"
	TukuiConfigUILocalization.miscsesset2 = "Set Set for second Spec"
	TukuiConfigUILocalization.miscsescastbar = "Enable castbar on Specswitcher"
	TukuiConfigUILocalization.miscilvlcharacter = "Enable display for itemlevel / durability on Characterscreen"

	TukuiConfigUILocalization.aurasremindersound = "Enable sound for Selfbuffreminder"
	TukuiConfigUILocalization.aurasselfbufs = "Enable Selfbuffreminder"

	TukuiConfigUILocalization.actionbarshapeshiftmouseover = "Set Shapeshiftbar to mouseover"
	TukuiConfigUILocalization.actionbarshapeshiftborder = "Enable border for Shapeshiftbar"
	TukuiConfigUILocalization.actionbarbutton2 = "Hide button between the Datatextpanels"
	TukuiConfigUILocalization.actionbarrightbarsmouseover = "Set rightbars to mouseover"
	TukuiConfigUILocalization.actionbarmacro = "Enable Highlightning for Provs in macros"
	TukuiConfigUILocalization.actionbarpetbaralwaysvisible = "Show always the petbar"
	TukuiConfigUILocalization.actionbarverticalshapeshift = "Set Shapeshiftbar vertical"
	TukuiConfigUILocalization.actionbarswapbar1and3 = "Swaps mainbar with bar3 on top"
	TukuiConfigUILocalization.actionbarpetbarhorizontal = "Set Petbar horizontal"
	TukuiConfigUILocalization.actionbarlayout = "Set Actionbarlayout"

	TukuiConfigUILocalization.chatfading = "Enable Chatfading"
	TukuiConfigUILocalization.chattextright = "Set text to right in the right chatframe"

	TukuiConfigUILocalization.duffed = "Duffed"
	TukuiConfigUILocalization.duffedannouncechannel = "Set announcechannel (SAY, PARTY, RAID)"
	TukuiConfigUILocalization.duffedpriest_sos = "Enable Strength of Soul-Plugin (Priest only)"
	TukuiConfigUILocalization.duffedsayinterrupt = "Enable Interruptannouncement"
	TukuiConfigUILocalization.duffeddispelannouncement = "Enable Dispelannouncement"
	TukuiConfigUILocalization.duffedarenaonly = "Enable Announcement only in Arena"
	TukuiConfigUILocalization.duffeddrinkannouncement = "Enable Drinkannouncement"
	TukuiConfigUILocalization.duffedccannouncement = "Enable Aura / CC-Announcement"
	
	-- general
	TukuiConfigUILocalization.general = "Allgemein"
	TukuiConfigUILocalization.generalautoscale = "Nutze automatische UI-Skalierung"
	TukuiConfigUILocalization.generaloverridelowtohigh = "Nutze Layout für hohe auf niedriger Auflösung"
	TukuiConfigUILocalization.generalmultisampleprotect = "Multisampling Schutz (sauberer 1px Ränder)"
	TukuiConfigUILocalization.generaluiscale = "UI Skalierung (Wenn Autoskalierung deaktiviert ist)"
	TukuiConfigUILocalization.generalbackdropcolor = "Hintergrundfarbe der Panels"
	TukuiConfigUILocalization.generalbordercolor = "Randfarbe der Panels"
	TukuiConfigUILocalization.generalblizzardreskin = "Änder Blizzardframes so das sie Aussehen wie Tukui"
	 
	-- nameplate
	TukuiConfigUILocalization.nameplate = "Namensplaketten"
	TukuiConfigUILocalization.nameplateenable = "Aktiviere Namensplaketten"
	TukuiConfigUILocalization.nameplateenhancethreat = "Aktiviere Bedrohungsanzeige, ändert sich automatisch nach Rolle"
	TukuiConfigUILocalization.nameplateshowhealth = "Zeige Leben an Namensplaketten"
	TukuiConfigUILocalization.nameplatecombat = "Zeige nur feindliche Namensplaketten im Kampf"
	TukuiConfigUILocalization.nameplategoodcolor = "Farbe für gute Bedrohung, hängt davon ab ob du Tank oder Heiler/DDler bist"
	TukuiConfigUILocalization.nameplatebadcolor = "Farbe für schlechte Bedrohung, hängt davon ab ob du Tank oder Heiler/DDler bist"
	TukuiConfigUILocalization.nameplatetransitioncolor = "Farbe für verlieren/erhalten von Bedrohnung"
	 
	-- merchant
	TukuiConfigUILocalization.merchant = "Händler"
	TukuiConfigUILocalization.merchantsellgrays = "Automatisch graue Gegenstände verkaufen"
	TukuiConfigUILocalization.merchantautorepair = "Automatisch alle Gegenstände reparieren"
	TukuiConfigUILocalization.merchantsellmisc = "Verkaufe vordefenierte (nutzlose, nicht graue) Gegenstände automatisch"
	 
	-- bags
	TukuiConfigUILocalization.bags = "Taschen"
	TukuiConfigUILocalization.bagsenable = "Aktiviere All-In-One Taschen"
	 
	-- datatext
	TukuiConfigUILocalization.datatext = "Infotext"
	TukuiConfigUILocalization.datatexttime24 = "Aktiviere 24-Stunden-Zeitanzeige"
	TukuiConfigUILocalization.datatextlocaltime = "Zeige Ortszeit, anstelle von Serverzeit"
	TukuiConfigUILocalization.datatextbattleground = "Aktiviere Schlachtfeld Anzeige"
	TukuiConfigUILocalization.datatexthps_text = "Heilung pro Sekunde, Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextguild = "Gilde Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatext_arp = "Rüstungsdurchschlag Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextsystem = "Speicher Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextbags = "Taschen Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextfontsize = "Schriftgröße des Text"
	TukuiConfigUILocalization.datatextfps_ms = "Latenz und FPS Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextarmor = "Rüstung Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextavd = "Vermeidung position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextpower = "Zaubermacht/Angriffskraft Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatexthaste = "Tempowertung Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextfriends = "Freunde Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextwowtime = "Zeit Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextgold = "Gold Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextdps_text = "Schaden pro Sekunde Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextcrit = "Crit % position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextdur = "Haltbarkeit Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextcurrency = "Währung Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextmicromenu = "Micro Menu Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatexthit = "Trefferwertung Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextmastery = "Meisterschaft Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatexttalent = "Zeige Spezalisierung (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextcalltoarms = "Ruf zu den Waffen & Dungeons (0 für deaktiviert)"

	 
	-- unit frames
	TukuiConfigUILocalization.unitframes = "Einheitenfenster"
	TukuiConfigUILocalization.unitframescombatfeedback = "Kampfmeldungen auf Spieler und Ziel"
	TukuiConfigUILocalization.unitframesrunebar = "Aktiviere Runenleiste für Todesritter"
	TukuiConfigUILocalization.unitframesauratimer = "Aktiviere Dauer auf Stärkungs- und Schwächungszaubern"
	TukuiConfigUILocalization.unitframestotembar = "Aktiviere Totemleiste für Schamanen"
	TukuiConfigUILocalization.unitframesshowtotalhpmp = "Zeige gesamtes Leben/Mana an"
	TukuiConfigUILocalization.unitframesshowplayerinparty = "Zeige sich selbst in der Gruppe"
	TukuiConfigUILocalization.unitframesraidunitdebuffwatch = "Aktiviere PvE Überwachung von Stärkungs- und Schwächungszaubern (nur Grid)"
	TukuiConfigUILocalization.unitframesunitcastbar = "Aktiviere Zauberleiste"
	TukuiConfigUILocalization.unitframestargetauras = "Aktiviere Stärkungs- und Schwächungszauber auf dem Ziel"
	TukuiConfigUILocalization.unitframessaveperchar = "Positionen der Einheitenfenster pro Charakter speichern"
	TukuiConfigUILocalization.unitframesplayeraggro = "Aktiviere Bedrohungsanzeige"
	TukuiConfigUILocalization.unitframesshowsmooth = "Aktiviere flüssigere Leistenänderungen"
	TukuiConfigUILocalization.unitframescharportrait = "Aktiviere Portrait für Spieler und Ziel"
	TukuiConfigUILocalization.unitframesenable = "Aktiviere Tukui Einheitenfenster"
	TukuiConfigUILocalization.unitframestargetpowerpvponly = "Zeige Mana/Wut/Energie nur bei Gegnern an"
	TukuiConfigUILocalization.unitframesgridonly = "Aktiviere Grid nur für das Heilerlayout"
	TukuiConfigUILocalization.unitframeshealcomm = "Aktiviere HealCom"
	TukuiConfigUILocalization.unitframesfocusdebuff = "Aktiviere Anzeige von Schwächungszauber auf Fokusziel"
	TukuiConfigUILocalization.unitframesaggro = "Aktiviere Bedrohungsanzeige des Schlachtzugs/Gruppe"
	TukuiConfigUILocalization.unitframesshowboss = "Aktiviere Einheitsfenster von Bossen"
	TukuiConfigUILocalization.unitframesenemyhcolor = "Färbe Lebensbalken der Gegner nach Feindseligkeit (für PVP)"
	TukuiConfigUILocalization.unitframesgridhealthvertical = "Lebensbalken bei Grid vertikal anzeigen"
	TukuiConfigUILocalization.unitframesshowsymbols = "Zeige Symbole bei Gruppe/Schlachtzug"
	TukuiConfigUILocalization.unitframesthreatbar = "Aktiviere Bedrohungsleiste"
	TukuiConfigUILocalization.unitframesshowrange = "Aktiviere Entfernungsanzeige für Schlachtzug/Gruppe"
	TukuiConfigUILocalization.unitframesfocus = "Aktiviere Fokusziel"
	TukuiConfigUILocalization.unitframescblatency = "Zeige Zauberleistenlatenz"
	TukuiConfigUILocalization.unitframescbicons = "Zeige Icons an der Zauberleiste"
	TukuiConfigUILocalization.unitframesplayerauras = "Aktiviere alternativen Stärkungs-/Schwächungszauber-Modus für Spieler"
	TukuiConfigUILocalization.unitframesauratextscale = "Textskalierung auf  Stärkungs-/Schwächungszaubern"
	TukuiConfigUILocalization.unitframesgridscale = "Grid Skalierung"
	TukuiConfigUILocalization.unitframesmanahigh = "Hohes Mana Indikator (für Jäger)"
	TukuiConfigUILocalization.unitframeslowThreshold = "Wenig Mana Indikator (Für alle Mana Klassen)"
	TukuiConfigUILocalization.unitframesraidalphaoor = "Transparenz der Schlachtzug- und Gruppenfenster wenn außer Reichweite"
	TukuiConfigUILocalization.unitframesmaintank = "Main Tank Anzeige aktivieren"
	TukuiConfigUILocalization.unitframesmainassist = "Main Assist Anzeige aktivieren"
	TukuiConfigUILocalization.unitframesunicolor = "Einheitliches Farbschema (graue Lebensbalken) aktivieren"
	TukuiConfigUILocalization.unitframestotdebuffs = "Ziel vom Ziel Schwächungszauber anzeigen (hohe Auflösung)"
	TukuiConfigUILocalization.unitframesclassbar = "Aktiviere Klassenleiste"
	TukuiConfigUILocalization.unitframesweakenedsoulbar = "Aktiviere 'Geschwächte Seele' Anzeige (Priester)"
	TukuiConfigUILocalization.unitframesonlyselfdebuffs = "Zeigt nur deine debuffs auf dem Ziel an"
	TukuiConfigUILocalization.unitframesshowfocustarget = "Aktiviere Fokus Ziel"
	TukuiConfigUILocalization.unitframesbordercolor = "Rahmenfarbe der Panels"
	TukuiConfigUILocalization.unitframesmovecombobar = "Bewege die Kombopunkte vom Ziel (nur Schurke)"
	TukuiConfigUILocalization.unitframesclassiccombo = "Benutze klassische Kombopunktanzeige"
	TukuiConfigUILocalization.unitframesgridvertical = "Gridausrichtung vertikal anstatt horizontal"
	 
	-- loot
	TukuiConfigUILocalization.loot = "Beute"
	TukuiConfigUILocalization.lootlootframe = "Aktiviere Beutefenster"
	TukuiConfigUILocalization.lootautogreed = "Aktiviere automatisch-Gier Würfeln für grüne Gegenstände (falls max. Level erreicht)"
	TukuiConfigUILocalization.lootrolllootframe = "Aktiviere Würfelfenster"
	 
	-- invite
	TukuiConfigUILocalization.invite = "Einladung"
	TukuiConfigUILocalization.inviteautoaccept = "Einladungen von Freunden & Gildenmitgliedern automatisch annehmen"
	 
	-- tooltip
	TukuiConfigUILocalization.tooltip = "Tooltip"
	TukuiConfigUILocalization.tooltipenable = "Aktiviere Tooltip"
	TukuiConfigUILocalization.tooltiphidecombat = "Verstecke Tooltip in Kampf"
	TukuiConfigUILocalization.tooltiphidebuttons = "Verstecke Tooltip an Aktionsleisten"
	TukuiConfigUILocalization.tooltiphideuf = "Verstecke Tooltip an Einheitenfenstern"
	TukuiConfigUILocalization.tooltipcursor = "Tooltip am Mauszeiger anzeigen"
	 
	-- error
	TukuiConfigUILocalization.error = "Fehlermeldung"
	TukuiConfigUILocalization.errorenable = "Verstecke rote Meldungen in der Mitte des Bildschirms"
	 
	-- action bar
	TukuiConfigUILocalization.actionbar = "Aktionsleisten"
	TukuiConfigUILocalization.actionbarhideshapeshift = "Verstecke Gestaltenwandler- oder Totemleiste"
	TukuiConfigUILocalization.actionbarshowgrid = "Rahmen auf Aktionsleisten immer anzeigen"
	TukuiConfigUILocalization.actionbarenable = "Aktiviere Tukui Aktionsleisten"
	TukuiConfigUILocalization.actionbarrb = "Aktiviere Mouseover für rechte Aktionsleisten"
	TukuiConfigUILocalization.actionbarhotkey = "Zeige Tastenbelegung auf den Buttons"
	TukuiConfigUILocalization.actionbarssmo = "Gestaltenwandler- oder Totemleiste nur bei Mouseover anzeigen"
	TukuiConfigUILocalization.actionbarrbn = "Anzahl der Aktionsleisten unten (1 oder 2)"
	TukuiConfigUILocalization.actionbarrn = "Anzahl der Aktionsleisten rechts (1, 2 oder 3)"
	TukuiConfigUILocalization.actionbarbuttonsize = "Größe der Aktionsleisten Buttons"
	TukuiConfigUILocalization.actionbarbuttonspacing = "Abstand der Aktionsleisten Buttons"
	TukuiConfigUILocalization.actionbarpetbuttonsize = "Größe der Begleiter/Gestaltenwandler Buttons"
	TukuiConfigUILocalization.actionbarownshdbar = "Benutze eine leer Leiste für Schattentanz (Schurke) Anstatt der Verstohlenheitsleiste"
	 
	-- arena
	TukuiConfigUILocalization.arena = "Arena"
	TukuiConfigUILocalization.arenaunitframes = "Aktiviere Arenaeinheitenfenster"
	 
	-- cooldowns
	TukuiConfigUILocalization.cooldown = "Abklingzeiten"
	TukuiConfigUILocalization.cooldownenable = "Aktiviere Anzeige der Abklingzeit auf Buttons"
	TukuiConfigUILocalization.cooldowntreshold = "Färbe Anzeige der Abklingzeiten ab Wert X rot"
	 
	-- chat
	TukuiConfigUILocalization.chat = "Geselligkeit"
	TukuiConfigUILocalization.chatenable = "Aktiviere Tukui Chat"
	TukuiConfigUILocalization.chatwhispersound = "Beim Empfang von Flüsternachrichten Ton abspielen"
	TukuiConfigUILocalization.chatbackground = "Aktiviere die Hintergrundpanel der Chatfenster"

	-- buff
	TukuiConfigUILocalization.auras = "Auren"
	TukuiConfigUILocalization.aurasplayer = "Aktiviere Tukui Stärkungs/Schwächungszauberanzeige"
	TukuiConfigUILocalization.aurasconsolidate = "Aktiviere zusammengelegte Stärkungszauber"
	TukuiConfigUILocalization.aurasflash = "Aktivieren blinkende Animation für Auren mit weniger als 30 Sekunden"

	-- buttons
	TukuiConfigUILocalization.option_button_reset = "Zurücksetzen"
	TukuiConfigUILocalization.option_button_load = "Anwenden"
	TukuiConfigUILocalization.option_button_close = "Schließen"
	TukuiConfigUILocalization.option_setsavedsetttings = "Einstellungen pro Charakter speichern"
	TukuiConfigUILocalization.option_resetchar = "Bist du sicher, dass du die Einstellungen für diesen Charakter auf Standard zurücksetzen willst?"
	TukuiConfigUILocalization.option_resetall = "Bist du sicher, dass du alle Einstellungen auf Standard zurücksetzen willst?"
	TukuiConfigUILocalization.option_perchar = "Bist du sicher, dass du die Einstellung für 'Einstellungen pro Charakter' wechseln willst?"
	TukuiConfigUILocalization.option_makeselection = "Du musst erst eine Auswahl treffen bevor Du mit den Einstellungen fortfahren können."
end