if GetLocale() == "ptBR" then
	-- translated by ?

	-- DuffedUI
	TukuiConfigUILocalization.nameplatedebuffs = "Enable Debufftracking on Nameplates"

	TukuiConfigUILocalization.merchantautoguildrepair = "Enable automatic repair from Guildbank (if it possible)"

	TukuiConfigUILocalization.generalnormalfont = "Use normal font instead of pixelfont"
	TukuiConfigUILocalization.generalthreatbar = "Set threatbar to the right Chattabbackground"
	TukuiConfigUILocalization.generaloverridehightolow = "Use Lowres-Layout on Highres"

	TukuiConfigUILocalization.bagsmoveable = "Enable moveable Bags"
	TukuiConfigUILocalization.bagstransparent = "Enable transparent Bagbackground"

	TukuiConfigUILocalization.datatexthonor = "Honor position (0 for disabled)"
	TukuiConfigUILocalization.datatexthonorablekills = "Honorable Kill position (0 for disabled)"
	TukuiConfigUILocalization.datatextclasscolor = "Set textelements to classcolor"
	TukuiConfigUILocalization.datatextblock = "Block position (0 for disabled)"
	TukuiConfigUILocalization.datatextexperience = "Experience position (0 for disabled)"
	TukuiConfigUILocalization.datatextdodge = "Dodge position (0 for disabled)"
	TukuiConfigUILocalization.datatextreputation = "Reputation position (0 for disabled)"
	TukuiConfigUILocalization.datatextmmenu = "Shows mMenu datatext (required: mMenu AddOn)"
	TukuiConfigUILocalization.datatextcolor1 = "Set color for datatext title (is overwritten if classcolor = true)"
	TukuiConfigUILocalization.datatextcolor2 = "Set color for datatext results"
	TukuiConfigUILocalization.datatextoutline = "Set outline for textelements"

	TukuiConfigUILocalization.unitframeshealthbarcolor = "Set healthbarcolor"
	TukuiConfigUILocalization.unitframesframewidth = "Set framewidth for player & target"
	TukuiConfigUILocalization.unitframesportraitstyle = "Set Portraitstyle (ICON or MODEL)"
	TukuiConfigUILocalization.unitframesdeficitcolor = "Set deficit color"
	TukuiConfigUILocalization.unitframesfader_alpha = "Set Alphavalue for fader"
	TukuiConfigUILocalization.unitframesdebuffrows = "Set debuffrows above target"
	TukuiConfigUILocalization.unitframeslayout = "Set layout for Unitframes (1, 2 or 3)"
	TukuiConfigUILocalization.unitframestotandpetlines = "Enable lines for ToT and Pet"
	TukuiConfigUILocalization.unitframespowerClasscolored = "Set powerbar to classcolor"
	TukuiConfigUILocalization.unitframespercent = "Display percentvalue beside the target & player"
	TukuiConfigUILocalization.unitframesColorGradient = "Enable colorgradient for unitframes"
	TukuiConfigUILocalization.unitframesvengeancebar = "Display vengence instead of threat"
	TukuiConfigUILocalization.unitframesfocusdebuffs = "Enable focus debuffs"
	TukuiConfigUILocalization.unitframeslargefocus = "Enable large focusframe (layout 1 & 2)"
	TukuiConfigUILocalization.unitframesfader = "Enable fader for unitframes (out of combat)"
	TukuiConfigUILocalization.unitframesgridsolo = "Show Grid always"
	TukuiConfigUILocalization.unitframeshidepp = "Hide Partypets on Heallayout"

	TukuiConfigUILocalization.skins = "Skins"
	TukuiConfigUILocalization.skinsdxe = "Enable DXE-Skin"
	TukuiConfigUILocalization.skinsdbm = "Enable DBM-Skin"
	TukuiConfigUILocalization.skinstinydps = "Enable TinyDPS-Skin"
	TukuiConfigUILocalization.skinsbigwigs = "Enable BigWigs-Skin"
	TukuiConfigUILocalization.skinsblizzard = "Enable Blizzard-Skin"
	TukuiConfigUILocalization.skinsskada = "Enable Skada-Skin"
	TukuiConfigUILocalization.skinsomen = "Enable Omen-Skin"
	TukuiConfigUILocalization.skinsrecount = "Enable Recountskin"
	TukuiConfigUILocalization.skinsbackground = "Enable Addonbackground"
	TukuiConfigUILocalization.skinstoggle = "Toggle AddonBackground in- / outfight"

	TukuiConfigUILocalization.rcd = "RaidCooldowns"
	TukuiConfigUILocalization.rcdenable = "Enable Raidcooldownmonitor"
	TukuiConfigUILocalization.rcdraid = "Enable Raid-Output"
	TukuiConfigUILocalization.rcdparty = "Enable Party-Output"
	TukuiConfigUILocalization.rcdarena = "Enable PvP-Output"

	TukuiConfigUILocalization.tooltipilvl = "Displays average itemlevel on tooltip"
	TukuiConfigUILocalization.tooltipshowspellid = "Show SpellID on tooltip"

	TukuiConfigUILocalization.castbar = "Castbar"
	TukuiConfigUILocalization.castbarenable = "Enable castbar"
	TukuiConfigUILocalization.castbarcblatency = "Show cast bar latency"
	TukuiConfigUILocalization.castbarcbicons = "Show icons on cast bar"
	TukuiConfigUILocalization.castbarfocuswidth = "Set width of focuscastbar"

	TukuiConfigUILocalization.classtimer = "Classtimer"
	TukuiConfigUILocalization.classtimerenable = "Enable Classtimer"
	TukuiConfigUILocalization.classtimertargetdebuffcolor = "Set color for debuffbars"
	TukuiConfigUILocalization.classtimertargetdebuffs = "Enable bars above targetdebuffs (not recommended)"
	TukuiConfigUILocalization.classtimertrinketcolor = "Set color for trinketbars"
	TukuiConfigUILocalization.classtimerplayercolor = "Set color for playerbars"
	TukuiConfigUILocalization.classtimertargetbuffcolor = "Set color for target buffbars"

	TukuiConfigUILocalization.misc = "Misc Options"
	TukuiConfigUILocalization.miscsesenable = "Enable Specswitcher"
	TukuiConfigUILocalization.miscsesgearswap = "Enable automatic gearswap @respec"
	TukuiConfigUILocalization.miscsComboenergybar = "Enable Energybar on sCombo"
	TukuiConfigUILocalization.miscsesset1 = "Set set fpr Mainspec"
	TukuiConfigUILocalization.miscsComboenable = "Enable sCombo"
	TukuiConfigUILocalization.miscsesenablegear = "Enable gearset for Specswitcher"
	TukuiConfigUILocalization.miscbossicons = "Enable alternativ bossicons"
	TukuiConfigUILocalization.miscsesset2 = "Set Set for second Spec"
	TukuiConfigUILocalization.miscsescastbar = "Enable castbar on Specswitcher"
	TukuiConfigUILocalization.miscilvlcharacter = "Enable display for itemlevel / durability on Characterscreen"
	TukuiConfigUILocalization.misccombatanimation = "Enable animation for entering or leaving combat"

	TukuiConfigUILocalization.aurasremindersound = "Enable sound for Selfbuffreminder"
	TukuiConfigUILocalization.aurasselfbufs = "Enable Selfbuffreminder"

	TukuiConfigUILocalization.actionbarshapeshiftmouseover = "Set Shapeshiftbar to mouseover"
	TukuiConfigUILocalization.actionbarshapeshiftborder = "Enable border for Shapeshiftbar"
	TukuiConfigUILocalization.actionbarbutton2 = "Hide button between the Datatextpanels"
	TukuiConfigUILocalization.actionbarrightbarsmouseover = "Set rightbars to mouseover"
	TukuiConfigUILocalization.actionbarmacro = "Enable Highlightning for Procs in macros"
	TukuiConfigUILocalization.actionbarpetbaralwaysvisible = "Show always the petbar"
	TukuiConfigUILocalization.actionbarverticalshapeshift = "Set Shapeshiftbar vertical"
	TukuiConfigUILocalization.actionbarswapbar1and3 = "Swaps mainbar with bar3 on top"
	TukuiConfigUILocalization.actionbarpetbarhorizontal = "Set Petbar horizontal"
	TukuiConfigUILocalization.actionbarlayout = "Set Actionbarlayout"
	TukuiConfigUILocalization.actionbarmacrotext = "Enable macrotext on actionbuttons"

	TukuiConfigUILocalization.chatfading = "Enable Chatfading"
	TukuiConfigUILocalization.chattextright = "Set text to right in the right chatframe"
	TukuiConfigUILocalization.chatbackgroundwidth = "Set width for chatbackground (one option for both panels)"
	TukuiConfigUILocalization.chatbackgroundheight = "Set height for chatbackground (one option for both panels)"

	TukuiConfigUILocalization.duffed = "Duffed"
	TukuiConfigUILocalization.duffedannouncechannel = "Set announcechannel (SAY, PARTY, RAID)"
	TukuiConfigUILocalization.duffedpriest_sos = "Enable Strength of Soul-Plugin (Priest only)"
	TukuiConfigUILocalization.duffedsayinterrupt = "Enable Interruptannouncement"
	TukuiConfigUILocalization.duffeddispelannouncement = "Enable Dispelannouncement"
	TukuiConfigUILocalization.duffedarenaonly = "Enable Announcement only in Arena"
	TukuiConfigUILocalization.duffeddrinkannouncement = "Enable Drinkannouncement"
	TukuiConfigUILocalization.duffedccannouncement = "Enable Aura / CC-Announcement"
	
	-- general
	TukuiConfigUILocalization.general = "General"
	TukuiConfigUILocalization.generalautoscale = "Auto UI Scale"
	TukuiConfigUILocalization.generaloverridelowtohigh = "Use High resolution  layout on a Lower resolution"
	TukuiConfigUILocalization.generalmultisampleprotect = "Multisampling protection (clean 1px border)"
	TukuiConfigUILocalization.generaluiscale = "UI Scale (if auto-scale is disabled)"
	TukuiConfigUILocalization.generalbackdropcolor = "Set default backdrop color of panels"
	TukuiConfigUILocalization.generalbordercolor = "Set default border color of panels"
	TukuiConfigUILocalization.generalblizzardreskin = "Reskin Blizzard frames to match Tukui"
	 
	-- nameplate
	TukuiConfigUILocalization.nameplate = "Nameplates"
	TukuiConfigUILocalization.nameplateenable = "Enable Nameplates"
	TukuiConfigUILocalization.nameplateenhancethreat = "Enable threat feature, automatically changes by your role"
	TukuiConfigUILocalization.nameplateshowhealth = "Show health on nameplate"
	TukuiConfigUILocalization.nameplatecombat = "Only show enemy nameplates in-combat"
	TukuiConfigUILocalization.nameplategoodcolor = "Good threat color, varies depending if your a tank or dps/heal"
	TukuiConfigUILocalization.nameplatebadcolor = "Bad threat color, varies depending if your a tank or dps/heal"
	TukuiConfigUILocalization.nameplatetransitioncolor = "Losing/Gaining threat color"
	 
	-- merchant
	TukuiConfigUILocalization.merchant = "Merchant"
	TukuiConfigUILocalization.merchantsellgrays = "Auto sell grey items"
	TukuiConfigUILocalization.merchantautorepair = "Auto Repair items"
	TukuiConfigUILocalization.merchantsellmisc = "Sell some defined (craps not grey) items automatically"
	 
	-- bags
	TukuiConfigUILocalization.bags = "Bags"
	TukuiConfigUILocalization.bagsenable = "Enable all-in-one bag"
	 
	-- datatext
	TukuiConfigUILocalization.datatext = "Data Text"
	TukuiConfigUILocalization.datatexttime24 = "Enable 24h time"
	TukuiConfigUILocalization.datatextlocaltime = "Use Local Time instead of Server Time"
	TukuiConfigUILocalization.datatextbattleground = "Enable Battleground Stats"
	TukuiConfigUILocalization.datatexthps_text = "Healing per second, position (0 for disabled)"
	TukuiConfigUILocalization.datatextguild = "Guild position (0 for disabled)"
	TukuiConfigUILocalization.datatext_arp = "Armor penetration position (0 for disabled)"
	TukuiConfigUILocalization.datatextsystem = "Memory position (0 for disabled)"
	TukuiConfigUILocalization.datatextbags = "Bags position (0 for disabled)"
	TukuiConfigUILocalization.datatextfontsize = "Font size of text"
	TukuiConfigUILocalization.datatextfps_ms = "Latency and FPS position (0 for disabled)"
	TukuiConfigUILocalization.datatextarmor = "Armor Position (0 for disabled)"
	TukuiConfigUILocalization.datatextavd = "Avoidance position (0 for disabled)"
	TukuiConfigUILocalization.datatextpower = "Power position (0 for disabled)"
	TukuiConfigUILocalization.datatexthaste = "Haste position (0 for disabled)"
	TukuiConfigUILocalization.datatextfriends = "Friends position (0 for disabled)"
	TukuiConfigUILocalization.datatextwowtime = "Time position (0 for disabled)"
	TukuiConfigUILocalization.datatextgold = "Gold position (0 for disabled)"
	TukuiConfigUILocalization.datatextdps_text = "Damage per second position (0 for disabled)"
	TukuiConfigUILocalization.datatextcrit = "Crit % position (0 for disabled)"
	TukuiConfigUILocalization.datatextdur = "Durability position (0 for disabled)"
	TukuiConfigUILocalization.datatextcurrency = "Currency position (0 for disabled)"
	TukuiConfigUILocalization.datatextmicromenu = "Micro Menu position (0 for disabled)"
	TukuiConfigUILocalization.datatexthit = "Hit position (0 for disabled)"
	TukuiConfigUILocalization.datatextmastery = "Mastery position (0 for disabled)"
	TukuiConfigUILocalization.datatexttalent = "Display talents (0 for disabled)"
	TukuiConfigUILocalization.datatextcalltoarms = "Call to Arms & Dungeons (0 for disabled)"
	TukuiConfigUILocalization.unitframesmovecombobar = "Move the combo bar from target (ROGUE ONLY)"
	TukuiConfigUILocalization.unitframesclassiccombo = "Use classic combo point"
	TukuiConfigUILocalization.unitframesgridvertical = "Display raid groups on Grid vertically"

	 
	-- unit frames
	TukuiConfigUILocalization.unitframes = "Unit Frames"
	TukuiConfigUILocalization.unitframescombatfeedback = "Combat Feedback on player and target"
	TukuiConfigUILocalization.unitframesrunebar = "Enable rune bar for Death Knight"
	TukuiConfigUILocalization.unitframesauratimer = "Enable timer on auras"
	TukuiConfigUILocalization.unitframestotembar = "Enable totem bar for Shaman"
	TukuiConfigUILocalization.unitframesshowtotalhpmp = "Display total of health/power"
	TukuiConfigUILocalization.unitframesshowplayerinparty = "Show yourself in party"
	TukuiConfigUILocalization.unitframesraidunitdebuffwatch = "Enable PVE raid Aura Watch (Grid Only)"
	TukuiConfigUILocalization.unitframesunitcastbar = "Enable cast bar"
	TukuiConfigUILocalization.unitframestargetauras = "Enable target auras"
	TukuiConfigUILocalization.unitframessaveperchar = "Save unit frames position per character"
	TukuiConfigUILocalization.unitframesplayeraggro = "Enable aggro display on yourself"
	TukuiConfigUILocalization.unitframesshowsmooth = "Enable smooth bar"
	TukuiConfigUILocalization.unitframescharportrait = "Enable portraits on player and target"
	TukuiConfigUILocalization.unitframesenable = "Enable Tukui Unit Frames"
	TukuiConfigUILocalization.unitframestargetpowerpvponly = "Enable Power display on enemy only"
	TukuiConfigUILocalization.unitframesgridonly = "Enable Grid only mode for Healer layout"
	TukuiConfigUILocalization.unitframeshealcomm = "Enable healcomm"
	TukuiConfigUILocalization.unitframesfocusdebuff = "Enable Focus debuffs"
	TukuiConfigUILocalization.unitframesaggro = "Enable aggro display on party/raid"
	TukuiConfigUILocalization.unitframesshowboss = "Enable Boss Unit Frames"
	TukuiConfigUILocalization.unitframesenemyhcolor = "Color enemy health bar by hostility (for PVP)"
	TukuiConfigUILocalization.unitframesgridhealthvertical = "Show health bar vertically for Grid layout"
	TukuiConfigUILocalization.unitframesshowsymbols = "Show symbols on party/raid"
	TukuiConfigUILocalization.unitframesthreatbar = "Enable threat bar"
	TukuiConfigUILocalization.unitframesshowrange = "Enable party/raid Range alpha display"
	TukuiConfigUILocalization.unitframesfocus = "Enable Focus target"
	TukuiConfigUILocalization.unitframescblatency = "Show cast bar latency"
	TukuiConfigUILocalization.unitframescbicons = "Show icons on cast bar"
	TukuiConfigUILocalization.unitframesplayerauras = "Enable an alternative aura mode for player"
	TukuiConfigUILocalization.unitframesauratextscale = "Aura text scale on auras"
	TukuiConfigUILocalization.unitframesgridscale = "Grid Scale"
	TukuiConfigUILocalization.unitframesmanahigh = "High mana indicator (For Hunters)"
	TukuiConfigUILocalization.unitframeslowThreshold = "Low mana indicator (All mana class)"
	TukuiConfigUILocalization.unitframesraidalphaoor = "Alpha on Party/Raid unit out of range"
	TukuiConfigUILocalization.unitframesmaintank = "Enable Main Tank"
	TukuiConfigUILocalization.unitframesmainassist = "Enable Main Assist"
	TukuiConfigUILocalization.unitframesunicolor = "Enable Unique color theme (grey health bar)"
	TukuiConfigUILocalization.unitframestotdebuffs = "Enable Target of Target debuffs (High Reso)"
	TukuiConfigUILocalization.unitframesclassbar = "Enable class bar"
	TukuiConfigUILocalization.unitframesweakenedsoulbar = "Enable Weakened Soul bar notification (Priest)"
	TukuiConfigUILocalization.unitframesonlyselfdebuffs = "Display only our debuffs on target"
	TukuiConfigUILocalization.unitframesshowfocustarget = "Enable Focus target"
	TukuiConfigUILocalization.unitframesbordercolor = "Set default border color of panels"
	 
	-- loot
	TukuiConfigUILocalization.loot = "Loot"
	TukuiConfigUILocalization.lootlootframe = "Enable loot window"
	TukuiConfigUILocalization.lootautogreed = "Enable auto-greed for green item at max level"
	TukuiConfigUILocalization.lootrolllootframe = "Enable item roll window"
	 
	-- invite
	TukuiConfigUILocalization.invite = "Invite"
	TukuiConfigUILocalization.inviteautoaccept = "Enable Auto-Invite (Friends and Guildmates)"
	 
	-- tooltip
	TukuiConfigUILocalization.tooltip = "Tooltip"
	TukuiConfigUILocalization.tooltipenable = "Enable tooltip"
	TukuiConfigUILocalization.tooltiphidecombat = "Hide tooltip in combat"
	TukuiConfigUILocalization.tooltiphidebuttons = "Hide tooltip on action bar buttons"
	TukuiConfigUILocalization.tooltiphideuf = "Hide tooltip on unit frames"
	TukuiConfigUILocalization.tooltipcursor = "Enable cursor tooltip"
	 
	-- error
	TukuiConfigUILocalization.error = "Error Message"
	TukuiConfigUILocalization.errorenable = "Hide spamming error in the middle of your screen"
	 
	-- action bar
	TukuiConfigUILocalization.actionbar = "Action Bars"
	TukuiConfigUILocalization.actionbarhideshapeshift = "Hide Shapeshift bar or Totem bar"
	TukuiConfigUILocalization.actionbarshowgrid = "Always show Grid on action bar"
	TukuiConfigUILocalization.actionbarenable = "Enable Tukui action bar"
	TukuiConfigUILocalization.actionbarrb = "Enable right bar on mouseover"
	TukuiConfigUILocalization.actionbarhotkey = "Show hotkey on buttons"
	TukuiConfigUILocalization.actionbarssmo = "Shapeshift bar or Totem bar on mouseover"
	TukuiConfigUILocalization.actionbarrbn = "Number of action bars on the bottom (1 or 2)"
	TukuiConfigUILocalization.actionbarrn = "Number of action bars on right (0, 1, 2 or 3)"
	TukuiConfigUILocalization.actionbarbuttonsize = "Size of the main action buttons"
	TukuiConfigUILocalization.actionbarbuttonspacing = "Spacing of the main action buttons"
	TukuiConfigUILocalization.actionbarpetbuttonsize = "Size of pet/shapeshift buttons"
	TukuiConfigUILocalization.actionbarownshdbar = "Use an empty bar for shadow dance (rogue) instead of stealth bar"
	 
	-- arena
	TukuiConfigUILocalization.arena = "Arena"
	TukuiConfigUILocalization.arenaunitframes = "Enable arena unit frames"
	 
	-- cooldowns
	TukuiConfigUILocalization.cooldown = "Cooldowns"
	TukuiConfigUILocalization.cooldownenable = "Enable cooldown number on buttons"
	TukuiConfigUILocalization.cooldowntreshold = "Turn cooldown number red at X value"
	 
	-- chat
	TukuiConfigUILocalization.chat = "Chat"
	TukuiConfigUILocalization.chatenable = "Enable Tukui Chat"
	TukuiConfigUILocalization.chatwhispersound = "Play sound when receiving private message"
	TukuiConfigUILocalization.chatbackground = "Enable chat panel background"

	-- buff
	TukuiConfigUILocalization.auras = "Auras"
	TukuiConfigUILocalization.aurasplayer = "Enable Tukui Buff/Debuff Frames"
	TukuiConfigUILocalization.aurasconsolidate = "Enable Consolidate Buffs"
	TukuiConfigUILocalization.aurasflash = "Enable flashing animation on aura less than 30 seconds"

	-- buttons
	TukuiConfigUILocalization.option_button_reset = "Reset"
	TukuiConfigUILocalization.option_button_load = "Apply Settings"
	TukuiConfigUILocalization.option_button_close = "Close"
	TukuiConfigUILocalization.option_setsavedsetttings = "Set settings Per-Character"
	TukuiConfigUILocalization.option_resetchar = "Are you sure you want to reset your character's settings to match your default settings?"
	TukuiConfigUILocalization.option_resetall = "Are you sure you want to reset all of your settings to Default?"
	TukuiConfigUILocalization.option_perchar = "Are you sure you want to change to or from 'Per Char Settings'?"
	TukuiConfigUILocalization.option_makeselection = "You must make a selection before you can continue to config."
end