if GetLocale() == "esES" or GetLocale() == "esMX" then
	-- translated by mrglmrgl
	-- based on esMX client

	-- DuffedUI
	TukuiConfigUILocalization.nameplatedebuffs = "Enable Debufftracking on Nameplates"

	TukuiConfigUILocalization.merchantautoguildrepair = "Enable automatic repair from Guildbank (if it possible)"

	TukuiConfigUILocalization.generalnormalfont = "Use normal font instead of pixelfont"
	TukuiConfigUILocalization.generalthreatbar = "Set threatbar to the right Chattabbackground"
	TukuiConfigUILocalization.generaloverridehightolow = "Use Lowres-Layout on Highres"

	TukuiConfigUILocalization.bagsmovable = "Enable moveable Bags"
	TukuiConfigUILocalization.bagstransparent = "Enable transparent Bagbackground"

	TukuiConfigUILocalization.datatexthonor = "Honor position (0 for disabled)"
	TukuiConfigUILocalization.datatexthonorablekills = "Honorable Kill position (0 for disabled)"
	TukuiConfigUILocalization.datatextclasscolor = "Set textelements to classcolor"
	TukuiConfigUILocalization.datatextblock = "Block position (0 for disabled)"
	TukuiConfigUILocalization.datatextexperience = "Experience position (0 for disabled)"
	TukuiConfigUILocalization.datatextdodge = "Dodge position (0 for disabled)"
	TukuiConfigUILocalization.datatextreputation = "Reputation position (0 for disabled)"
	TukuiConfigUILocalization.datatextmmenu = "Shows mMenu datatext (required: mMenu AddOn)"

	TukuiConfigUILocalization.unitframeshealthbarcolor = "Set healthbarcolor"
	TukuiConfigUILocalization.unitframesframewidth = "Set framewidth for player & target"
	TukuiConfigUILocalization.unitframesportraitstyle = "Set Portraitstyle (ICON or MODEL)"
	TukuiConfigUILocalization.unitframesdeficitcolor = "Set deficit color"
	TukuiConfigUILocalization.unitframesfader_alpha = "Set Alphavalue for fader"
	TukuiConfigUILocalization.unitframesdebuffrows = "Set debuffrows above target"
	TukuiConfigUILocalization.unitframeslayout = "Set layout for Unitframes (1, 2 or 3)"
	TukuiConfigUILocalization.unitframestotandpetlines = "Enable lines for ToT and Pet"
	TukuiConfigUILocalization.unitframespowerClasscolored = "Set powerbar to classcolor"
	TukuiConfigUILocalization.unitframespercent = "Display percentvalue beside the target & player"
	TukuiConfigUILocalization.unitframesColorGradient = "Enable colorgradient for unitframes"
	TukuiConfigUILocalization.unitframesvengeancebar = "Display vengence instead of threat"
	TukuiConfigUILocalization.unitframesfocusdebuffs = "Enable focus debuffs"
	TukuiConfigUILocalization.unitframeslargefocus = "Enable large focusframe (layout 1 & 2)"
	TukuiConfigUILocalization.unitframesfader = "Enable fader for unitframes (out of combat)"
	TukuiConfigUILocalization.unitframesgridsolo = "Show Grid always"

	TukuiConfigUILocalization.skins = "Skins"
	TukuiConfigUILocalization.skinsdxe = "Enable DXE-Skin"
	TukuiConfigUILocalization.skinsdbm = "Enable DBM-Skin"
	TukuiConfigUILocalization.skinstinydps = "Enable TinyDPS-Skin"
	TukuiConfigUILocalization.skinsbigwigs = "Enable BigWigs-Skin"
	TukuiConfigUILocalization.skinsblizzard = "Enable Blizzard-Skin"
	TukuiConfigUILocalization.skinsskada = "Enable Skada-Skin"
	TukuiConfigUILocalization.skinsomen = "Enable Omen-Skin"
	TukuiConfigUILocalization.skinsrecount = "Enable Recountskin"
	TukuiConfigUILocalization.skinsbackground = "Enable Addonbackground"
	TukuiConfigUILocalization.skinstoggle = "Toggle AddonBackground in- / outfight"

	TukuiConfigUILocalization.rcd = "RaidCooldowns"
	TukuiConfigUILocalization.rcdenable = "Enable Raidcooldownmonitor"
	TukuiConfigUILocalization.rcdraid = "Enable Raid-Output"
	TukuiConfigUILocalization.rcdparty = "Enable Party-Output"
	TukuiConfigUILocalization.rcdarena = "Enable PvP-Output"

	TukuiConfigUILocalization.tooltipilvl = "Displays average itemlevel on tooltip"
	TukuiConfigUILocalization.tooltipshowspellid = "Show SpellID on tooltip"

	TukuiConfigUILocalization.castbar = "Castbar"
	TukuiConfigUILocalization.castbarenable = "Enable castbar"
	TukuiConfigUILocalization.castbarcblatency = "Show cast bar latency"
	TukuiConfigUILocalization.castbarcbicons = "Show icons on cast bar"
	TukuiConfigUILocalization.castbarfocuswidth = "Set width of focuscastbar"

	TukuiConfigUILocalization.classtimer = "Classtimer"
	TukuiConfigUILocalization.classtimerenable = "Enable Classtimer"
	TukuiConfigUILocalization.classtimertargetdebuffcolor = "Set color for debuffbars"
	TukuiConfigUILocalization.classtimertargetdebuffs = "Enable bars above targetdebuffs (not recommended)"
	TukuiConfigUILocalization.classtimertrinketcolor = "Set color for trinketbars"
	TukuiConfigUILocalization.classtimerplayercolor = "Set color for playerbars"
	TukuiConfigUILocalization.classtimertargetbuffcolor = "Set color for target buffbars"

	TukuiConfigUILocalization.misc = "Misc Options"
	TukuiConfigUILocalization.miscsesenable = "Enable Specswitcher"
	TukuiConfigUILocalization.miscswingtimerenable = "Enable Swingtimer"
	TukuiConfigUILocalization.miscsesgearswap = "Enable automatic gearswap @respec"
	TukuiConfigUILocalization.miscsComboenergybar = "Enable Energybar on sCombo"
	TukuiConfigUILocalization.miscsesset1 = "Set set fpr Mainspec"
	TukuiConfigUILocalization.miscswingtimercolor = "Set color for Swingtimer"
	TukuiConfigUILocalization.miscsComboenable = "Enable sCombo"
	TukuiConfigUILocalization.miscswingtimerwidth = "Set width of Swingtimer"
	TukuiConfigUILocalization.miscsesenablegear = "Enable gearset for Specswitcher"
	TukuiConfigUILocalization.miscbossicons = "Enable alternativ bossicons"
	TukuiConfigUILocalization.miscswingtimerheight = "Set height for Swingtimer"
	TukuiConfigUILocalization.miscsesset2 = "Set Set for second Spec"
	TukuiConfigUILocalization.miscsescastbar = "Enable castbar on Specswitcher"
	TukuiConfigUILocalization.miscilvlcharacter = "Enable display for itemlevel / durability on Characterscreen"

	TukuiConfigUILocalization.aurasremindersound = "Enable sound for Selfbuffreminder"
	TukuiConfigUILocalization.aurasselfbufs = "Enable Selfbuffreminder"

	TukuiConfigUILocalization.actionbarshapeshiftmouseover = "Set Shapeshiftbar to mouseover"
	TukuiConfigUILocalization.actionbarshapeshiftborder = "Enable border for Shapeshiftbar"
	TukuiConfigUILocalization.actionbarbutton2 = "Hide button between the Datatextpanels"
	TukuiConfigUILocalization.actionbarrightbarsmouseover = "Set rightbars to mouseover"
	TukuiConfigUILocalization.actionbarmacro = "Enable Highlightning for Provs in macros"
	TukuiConfigUILocalization.actionbarpetbaralwaysvisible = "Show always the petbar"
	TukuiConfigUILocalization.actionbarverticalshapeshift = "Set Shapeshiftbar vertical"
	TukuiConfigUILocalization.actionbarswapbar1and3 = "Swaps mainbar with bar3 on top"
	TukuiConfigUILocalization.actionbarpetbarhorizontal = "Set Petbar horizontal"
	TukuiConfigUILocalization.actionbarlayout = "Set Actionbarlayout"

	TukuiConfigUILocalization.chatfading = "Enable Chatfading"
	TukuiConfigUILocalization.chattextright = "Set text to right in the right chatframe"

	TukuiConfigUILocalization.duffed = "Duffed"
	TukuiConfigUILocalization.duffedannouncechannel = "Set announcechannel (SAY, PARTY, RAID)"
	TukuiConfigUILocalization.duffedpriest_sos = "Enable Strength of Soul-Plugin (Priest only)"
	TukuiConfigUILocalization.duffedsayinterrupt = "Enable Interruptannouncement"
	TukuiConfigUILocalization.duffeddispelannouncement = "Enable Dispelannouncement"
	TukuiConfigUILocalization.duffedarenaonly = "Enable Announcement only in Arena"
	TukuiConfigUILocalization.duffeddrinkannouncement = "Enable Drinkannouncement"
	TukuiConfigUILocalization.duffedccannouncement = "Enable Aura / CC-Announcement"
	
	-- General
	TukuiConfigUILocalization.general = "General"
	TukuiConfigUILocalization.generalautoscale = "Autoajustar Escala IU"
	TukuiConfigUILocalization.generaloverridelowtohigh = "Usar entorno de Alta resolución en una resolución menor"
	TukuiConfigUILocalization.generalmultisampleprotect = "Protección de multimuestreo"
	TukuiConfigUILocalization.generaluiscale = "Escala de IU (si autoajustar escala está desactivado)"
	TukuiConfigUILocalization.generalbackdropcolor = "Establece el color predeterminado de fondo de los paneles"
	TukuiConfigUILocalization.generalbordercolor = "Establece el color predeterminado de bordes de los paneles"
	TukuiConfigUILocalization.generalblizzardreskin = "Ajusta los marcos de Blizzard para que coincidan visualmente con Tukui"

	-- Placas de Nombre
	TukuiConfigUILocalization.nameplate = "Placas de Nombre"
	TukuiConfigUILocalization.nameplateenable = "Activar Placas de nombre"
	TukuiConfigUILocalization.nameplateenhancethreat = "Activar función de amenaza, se ajusta automáticamente en base al rol"
	TukuiConfigUILocalization.nameplateshowhealth = "Mostrar Salud en Placas de Nombre"
	TukuiConfigUILocalization.nameplatecombat = "Solo Mostrar Placas de Nombre enemigas en combate"
	TukuiConfigUILocalization.nameplategoodcolor = "Color para nivel de amenaza bueno, varia dependiendo del rol (tanque  o daño/sanador)"
	TukuiConfigUILocalization.nameplatebadcolor = "Color para nivel de amenaza malo, varía dependiendo del rol (tanque  o daño/sanador)"
	TukuiConfigUILocalization.nameplatetransitioncolor = "Color para aumentando/disminuyendo nivel de amenaza"

	-- Vendedor
	TukuiConfigUILocalization.merchant = "Vendedor"
	TukuiConfigUILocalization.merchantsellgrays = "Vender automáticamente los objetos grises"
	TukuiConfigUILocalization.merchantautorepair = "Reparar objetos automáticamente"
	TukuiConfigUILocalization.merchantsellmisc = "Vender automáticamente objetos definidos (basura no grises)"

	-- Mochila
	TukuiConfigUILocalization.bags = "Mochila "
	TukuiConfigUILocalization.bagsenable = "Activar Mochila 'todo en uno'"

	-- Textos de Datos
	TukuiConfigUILocalization.datatext = "Textos de Datos"
	TukuiConfigUILocalization.datatexttime24 = "Mostrar hora en formato 24h"
	TukuiConfigUILocalization.datatextlocaltime = "Usar Hora Local en lugar de Hora del Servidor"
	TukuiConfigUILocalization.datatextbattleground = "Activar estadísticas de campos de batalla"
	TukuiConfigUILocalization.datatexthps_text = "Posición para 'Sanación por segundo', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextguild = "Posición para 'Clan', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatext_arp = "Posición para 'Penetración de Armadura', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextsystem = "Posición para 'Uso de Memoria', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextbags = "Posición para 'Inventario', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextfontsize = "Tamaño de fuente para Textos de Datos"
	TukuiConfigUILocalization.datatextfps_ms = "Posición para 'Latencia e Imágenes por Segundo', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextarmor = "Posición para 'Armadura', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextavd = "Posición para 'Evasión', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextpower = "Posición para 'Poder' (0 para deshabilitar)"
	TukuiConfigUILocalization.datatexthaste = "Posición para 'Celeridad', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextfriends = "Posición para 'Amigos', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextwowtime = "Posición para 'Reloj', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextgold = "Posición para 'Oro', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextdps_text = "Posición para 'Daño por Segundo', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextcrit = "Posición para '% de Crit', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextdur = "Posición para 'Durabilidad', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextcurrency = "Posición para 'Monedas', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextmicromenu = "Posición para 'Micro Menu', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatexthit = "Posición para 'Índice de Golpe', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextmastery = "Posición para 'Maestría', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatexttalent = "Posición para 'Mostrar Especialidad', (0 para deshabilitar)"
	TukuiConfigUILocalization.datatextcalltoarms = "Posición para 'Llamamiento a las Armas y Mazmorras', (0 para deshabilitar)"


	-- Marcos de Unidades
	TukuiConfigUILocalization.unitframes = "Marcos de Unidades"
	TukuiConfigUILocalization.unitframescombatfeedback = "Información de Combate en Jugador y Objetivo"
	TukuiConfigUILocalization.unitframesrunebar = "Activar barra de runas para el Caballero de la Muerte"
	TukuiConfigUILocalization.unitframesauratimer = "Activar temporizador en auras"
	TukuiConfigUILocalization.unitframestotembar = "Activar barra de totems para Chamán"
	TukuiConfigUILocalization.unitframesshowtotalhpmp = "Mostrar totales de Salud/Poder"
	TukuiConfigUILocalization.unitframesshowplayerinparty = "Mostrarte a tí mismo en el grupo"
	TukuiConfigUILocalization.unitframesraidunitdebuffwatch = "Activar monitor de auras de JcE (Cuadrícula solamente)"
	TukuiConfigUILocalization.unitframesunitcastbar = "Activar barra de lanzamiento"
	TukuiConfigUILocalization.unitframestargetauras = "Activar auras de Objetivo"
	TukuiConfigUILocalization.unitframessaveperchar = "Almacenar posición por personaje de marcos de unidades"
	TukuiConfigUILocalization.unitframesplayeraggro = "Activar 'Mostrar Agro' en tí mismo"
	TukuiConfigUILocalization.unitframesshowsmooth = "Activar barras fluidas"
	TukuiConfigUILocalization.unitframescharportrait = "Activar retratos en Jugador y Objetivo"
	TukuiConfigUILocalization.unitframesenable = "Activar los Marcos de Unidades de Tukui"
	TukuiConfigUILocalization.unitframestargetpowerpvponly = "Activar 'Mostrar Poder en enemigo solamente'"
	TukuiConfigUILocalization.unitframesgridonly = "Activar modo de Cuadrícula solamente para Entorno de Sanador"
	TukuiConfigUILocalization.unitframeshealcomm = "Activar healcomm"
	TukuiConfigUILocalization.unitframesfocusdebuff = "Activar 'Mostrar Prejuicios en Foco'"
	TukuiConfigUILocalization.unitframesaggro = "Activar 'Mostrar Agro en Grupo/Banda'"
	TukuiConfigUILocalization.unitframesshowboss = "Activar Marcos de Unidad de Jefes"
	TukuiConfigUILocalization.unitframesenemyhcolor = "Colorear la barra de salud por hostilidad (para JcJ)"
	TukuiConfigUILocalization.unitframesgridhealthvertical = "Mostrar barra de salud vertical para entorno de cuadrícula"
	TukuiConfigUILocalization.unitframesshowsymbols = "Mostrar símbolos en grupo/banda"
	TukuiConfigUILocalization.unitframesthreatbar = "Activa Barra de Amenaza"
	TukuiConfigUILocalization.unitframesshowrange = "Activa 'Modo de transparencia por distancia en grupo/banda"
	TukuiConfigUILocalization.unitframesfocus = "Activa objetivo de foco"
	TukuiConfigUILocalization.unitframescblatency = "Activa latencia en barra de lanzamiento"
	TukuiConfigUILocalization.unitframescbicons = "Mostrar íconos en barra de lanzamiento"
	TukuiConfigUILocalization.unitframesplayerauras = "Activa un modo alterno de auras para jugador"
	TukuiConfigUILocalization.unitframesauratextscale = "Escala de tamaño de texto en auras"
	TukuiConfigUILocalization.unitframesgridscale = "Escala de Cuadrícula"
	TukuiConfigUILocalization.unitframesmanahigh = "Indicador de Maná Alto (Para Cazadores)"
	TukuiConfigUILocalization.unitframeslowThreshold = "Indicador de Maná Bajo (Todas las clases que usan Maná)"
	TukuiConfigUILocalization.unitframesraidalphaoor = "Transparencia en unidad de grupo/banda fuera de rango"
	TukuiConfigUILocalization.unitframesmaintank = "Activar Tanque Principal"
	TukuiConfigUILocalization.unitframesmainassist = "Activar Asistente Principal"
	TukuiConfigUILocalization.unitframesunicolor = "Activar Tema de color único (barra de salud gris)"
	TukuiConfigUILocalization.unitframestotdebuffs = "Activar Prejuicios de Objetivo de Objetivo (Alta Resolución)"
	TukuiConfigUILocalization.unitframesclassbar = "Activar barra de clase"
	TukuiConfigUILocalization.unitframesweakenedsoulbar = "Activar notificación de Alma Debilitada (Sacerdote)"
	TukuiConfigUILocalization.unitframesonlyselfdebuffs = "Mostrar solo nuestros prejuicios en objetivo"
	TukuiConfigUILocalization.unitframesshowfocustarget = "Activar objetivo de foco"
	TukuiConfigUILocalization.unitframesbordercolor = "Establece color predeterminado de borde de paneles"
	TukuiConfigUILocalization.unitframesmovecombobar = "Mover la barra de combo del objetivo (PÍCARO SOLAMENTE)"
	TukuiConfigUILocalization.unitframesclassiccombo = "Usar barra de combo clásica"
	TukuiConfigUILocalization.unitframesgridvertical = "Mostrar grupos de banda en Cuadrícula verticálmente"

	-- Botín
	TukuiConfigUILocalization.loot = "Botín"
	TukuiConfigUILocalization.lootlootframe = "Activar Ventana de botín"
	TukuiConfigUILocalization.lootautogreed = "Activar 'Tirar por Codicia automáticamente' en objetos verdes en máximo nivel"
	TukuiConfigUILocalization.lootrolllootframe = "Activar Marco de Lanzamiento de Dados por Botín"

	-- Invitar
	TukuiConfigUILocalization.invite = "Invitar"
	TukuiConfigUILocalization.inviteautoaccept = "Activar Autoinvitar (Amigos y Compañeros de Clan)"

	-- Descripciones
	TukuiConfigUILocalization.tooltip = "Descripciones"
	TukuiConfigUILocalization.tooltipenable = "Activar Descripciones"
	TukuiConfigUILocalization.tooltiphidecombat = "Ocultar descripciones en combate"
	TukuiConfigUILocalization.tooltiphidebuttons = "Ocultar descripciones en barras de acción"
	TukuiConfigUILocalization.tooltiphideuf = "Ocultar descripciones en marcos de unidades"
	TukuiConfigUILocalization.tooltipcursor = "Activar descripción en cursor"

	-- error
	TukuiConfigUILocalization.error = "Mensaje de Error"
	TukuiConfigUILocalization.errorenable = "Ocultar spam de errores a la mitad de la pantalla"

	-- barra de acción
	TukuiConfigUILocalization.actionbar = "Barras de Acción"
	TukuiConfigUILocalization.actionbarhideshapeshift = "Ocultar Barra de Cambio de Forma/Totems"
	TukuiConfigUILocalization.actionbarshowgrid = "Siempre mostrar cuadrícula en las barras de acción"
	TukuiConfigUILocalization.actionbarenable = "Activar las Barras de Acción de Tukui"
	TukuiConfigUILocalization.actionbarrb = "Mostrar la barra de la derecha al pasar el cursor"
	TukuiConfigUILocalization.actionbarhotkey = "Mostrar teclas de acceso rápido en las barras de acción"
	TukuiConfigUILocalization.actionbarssmo = "Mostrar barra de cambio de forma/totems al pasar el cursor"
	TukuiConfigUILocalization.actionbarrbn = "Número de barras de acción abajo (1 o 2)"
	TukuiConfigUILocalization.actionbarrn = "Number de barras de acción a la derecha (0, 1, 2 o 3)"
	TukuiConfigUILocalization.actionbarbuttonsize = "Tamaño de los botones de acción principales"
	TukuiConfigUILocalization.actionbarbuttonspacing = "Espacio entre los botones de acción principales"
	TukuiConfigUILocalization.actionbarpetbuttonsize = "Tamaño de los botones de la barra de mascota/cambio de forma/tótems"
	TukuiConfigUILocalization.actionbarownshdbar = "Usar una barra bacía para 'Danza de las Sombras' (Pícaro) en lugar de la barra de sigilo"

	-- arena
	TukuiConfigUILocalization.arena = "Arena"
	TukuiConfigUILocalization.arenaunitframes = "Activar marcos de unidad de arena"

	-- Tiempos de Reutilización
	TukuiConfigUILocalization.cooldown = "Tiempos de Reutilización"
	TukuiConfigUILocalization.cooldownenable = "Mostrar tiempos de reutilización en botones"
	TukuiConfigUILocalization.cooldowntreshold = "Colorear en rojo el tiempo de reutilización al alcanzar el valor X"

	-- chat
	TukuiConfigUILocalization.chat = "Chat"
	TukuiConfigUILocalization.chatenable = "Activa el Chat de Tukui"
	TukuiConfigUILocalization.chatwhispersound = "Reproducir sonido al recibir mensaje privado"
	TukuiConfigUILocalization.chatbackground = "Habilitar fondo del panel de chat"

	-- Auras
	TukuiConfigUILocalization.auras = "Auras"
	TukuiConfigUILocalization.aurasplayer = "Activa los marcos de Beneficios/Prejuicios de Tukui"
	TukuiConfigUILocalization.aurasconsolidate = "Activa la consolidación de Beneficios"
	TukuiConfigUILocalization.aurasflash = "Activa la animación intermitente en auras con duración menor a 30 segundos"

	-- botones
	TukuiConfigUILocalization.option_button_reset = "Reiniciar"
	TukuiConfigUILocalization.option_button_load = "Aplicar cambios"
	TukuiConfigUILocalization.option_button_close = "Cerrar"
	TukuiConfigUILocalization.option_setsavedsetttings = "Ajustes por personaje"
	TukuiConfigUILocalization.option_resetchar = "¿Estás seguro que quieres reiniciar los ajustes de tu personaje para que coincidan con tus ajustes predeterminados?"
	TukuiConfigUILocalization.option_resetall = "¿Estás seguro de que quieres reiniciar todos tus ajustes a los predeterminados?"
	TukuiConfigUILocalization.option_perchar = "¿Estás seguro que quieres activar o desactivar los 'Ajustes por personaje'?"
	TukuiConfigUILocalization.option_makeselection = "Debes seleccionar una opción antes de continuar con la configuración"

end